AppBundle\Entity\Curso:
    properties:
        titulo:
            - NotBlank: {message: "El titulo no puede estar vacío"}
            - Length:
                min: 2
                minMessage: "El título de tener más de dos caracteres"
        descripcion:
            - NotBlank: {message: "La descripcion no puede estar vacía"}
        precio:
            - Type:
                type: numeric
                message: "El precio tiene que ser numérico"
